### ISSUE TITLE
Issue creating unit tests for stanza objects.

### ISSUE THREAD

**Issue by dannmartens** [fritzy/SleekXMPP#81] opened 2011-01-12 13:21 UTC
I have created tests for the stanza objects used in the new XEP-0009 (Jabber-RPC) plug-in, similar to those in the tests package (test_stanza_...).

Unfortunately, the test all fail on the 'second generated stanza, because an additional &lt;query xmlns="jabber:iq:rpc" /&gt; is generated. This problem is only seen with this type of test. The current plug-in implementation itself in operation works as expected (and with other unit tests).

For methodCall
--- SNIP ---

Second generated stanza:
&lt;iq xmlns="jabber:client" id="0"&gt;&lt;query xmlns="jabber:iq:rpc" /&gt;&lt;query xmlns="jabber:iq:rpc"&gt;&lt;methodCall&gt;&lt;methodName&gt;system.exit&lt;/methodName&gt;&lt;params /&gt;                    &lt;/methodCall&gt;&lt;/query&gt;&lt;/iq&gt;

--- SNIP ---

For methodResponse:
--- SNIP ---

Second generated stanza:
&lt;iq xmlns="jabber:client" id="0"&gt;&lt;query xmlns="jabber:iq:rpc" /&gt;&lt;query xmlns="jabber:iq:rpc"&gt;&lt;methodResponse&gt;&lt;params /&gt;                    &lt;/methodResponse&gt;&lt;/query&gt;&lt;/iq&gt;

--- SNIP ---

Can this be traced back to the fact that I'm using multiple classes to generate a single stanza?

class RPCQuery(ElementBase):
    name = 'query'
    namespace = 'jabber:iq:rpc'
    plugin_attrib = 'rpc_query'

class MethodCall(ElementBase):
    name = 'methodCall'
    namespace = 'jabber:iq:rpc'
    plugin_attrib = 'method_call'

class MethodResponse(ElementBase):
    name = 'methodResponse'
    namespace = 'jabber:iq:rpc'
    plugin_attrib = 'method_response'

register_stanza_plugin(Iq, RPCQuery)
register_stanza_plugin(RPCQuery, MethodCall)  
register_stanza_plugin(RPCQuery, MethodResponse)

Is this an improper use of stanza objects or is this an issue base class for testing?

**Comment by legastero** [comment] 2011-01-12 13:57
For now you can add use_values=False to the check method. I've encountered this problem before and it is caused by the iq['query'] and iq['rpc_query'] values being set in the wrong order.

**Comment by legastero** [comment] 2011-01-12 13:59
I just pushed a patch to fix that ordering issue, so that should solve the problem.

**Comment by dannmartens** [comment] 2011-01-12 15:25
Thanks Lance!

Unfortunately, no joy thus far.

The unit test failure points in the direction of XML not being matched as XML, but as raw strings: the whitespace introduces some dissonance:

--- SNIP ---

AssertionError: Two methods for creating stanzas do not match.
Given XML:

```
<iq xmlns="jabber:client" id="0">
            <query xmlns="jabber:iq:rpc">
                <methodResponse>
                    <params />
                </methodResponse>
            </query>
        </iq>
```

Given stanza:

```
<iq xmlns="jabber:client" id="0"><query xmlns="jabber:iq:rpc"><methodResponse><params />    </methodResponse></query></iq>
```

Generated stanza:

```
<iq xmlns="jabber:client" id="0">
            <query xmlns="jabber:iq:rpc">
                <methodResponse>
                    <params />
                </methodResponse>
            </query>
        </iq>
```

--- SNIP ---

As far as I can tell, these should check out okay!

**Comment by legastero** [comment] 2011-01-12 15:49
Ok, I'm pretty sure this is what is causing this new issue.

First, the unit tests don't do string matching for XML. Any strings are first converted to XML objects which are then compared. One step in that process is propagating namespaces to child elements.

The tostring method that converts XML objects to strings makes one assumption in how it should print, to make things prettier for debugging, and that is to only show namespaces on the top level element.

However, this hides issues like the one you're facing. You're using the old py2xml function to generate the <params /> data, but py2xml does not include the jabber:iq:rpc namespace in the elements it returns. Thus, the test fails because the expected &lt;params xmlns='jabber:iq:rpc' /&gt; is not the same as just &lt;params /&gt;.

I'll look into patching tostring to always print namespaces in tests.

**Comment by dannmartens** [comment] 2011-01-12 17:23
Hi Lance,

Actually, working with the available XML functions has been a recurring problem from the beginning of the overhaul.

I've had to update the xml2py functions already to take the namespace into account; otherwise, the original code wouldn't unmarshall the parameters.

There hasn't been any need to update the py2xml: the entire XEP-0009 plug-in works (with my tests) without having that changed.

However, I've changed the code to reflect your suggestion, it now sets the namespace explicitly, but it has no effect. My tests still run, but the stanza test still fails.

Admittedly, I have no experience with ElementTree. 

I've tried both:
- ET.Element("params", { 'xmlns', _namespace })
- ET.Element("{%s}params" % _namespace)

for all occurences of ET.Element inside py2xml/_py2xml

**Comment by legastero** [comment] 2011-01-12 18:05
Here is what I've tried:

Change xmlstream/xmlstream.py to remove imports for Waiter and MatchXMLMask (They will create circular dependencies if imported there -- fixed in develop branch)

Change params = ET.Element("params") to params = ET.Element("{jabber:iq:rpc}params") in old_0009.py in py2xml.

Add suite = unittest.TestLoader().loadTestsFromTestCase(TestJabberRPC) to the end of tests/test_stanza_xep_0009.py

Add import unittest to top of tests/test_stanza_xep_0009.py

After those changes, running python testall.py ran all tests successfully.

I should note that it would be best to work off of the develop branch instead of master. There have been quite a few changes and bugs fixed since the last beta release, some of which I noticed you applied partial fixes for in recent commits.

If errors still persist, then I'm not sure what would be the cause. I'll have to take some more time to review the new plugin further.

**Comment by dannmartens** [comment] 2011-01-13 07:41
Hi Lance,

Really puzzled by this.

Switched to develop, merged the changes but the test keeps failing.

**Comment by legastero** [comment] 2011-02-07 15:46
Now that everything has been merged in, I noticed that the tests were using code from old_0009 for the py2xml function. Importing the new version of py2xml from xep_0009.binding fixed the issue. So all tests pass once again.

I'm looking forward to playing/testing with this great new RPC functionality!

**Comment by dannmartens** [comment] 2011-02-07 15:48
Great,

Thanks for pinpointing the issue! I must have overlooked some imports!

Cheers,
 Dann

**Closed as completed** 2011-02-07 23:46 UTC
